### ISSUE TITLE
Action cannot handle latest json meta schema

### ISSUE THREAD

**Issue by JohnnyJayJay** [GrantBirki/json-yaml-validate#21]
The action has a [strange issue](https://github.com/codosseum-org/challenges/actions/runs/5798365904/job/15715938180) when the declared json schema uses the most recent meta schema in its `$schema` key. The schema can be found at http://json-schema.org/draft/2020-12/schema, and [here](https://github.com/codosseum-org/challenges/blob/c0e736069af45848cc2b4b49003783a2396599c3/challenge-schema.json) is the schema that used it and caused the action to fail.

The error (backtrace):
```
Error: no schema with key or ref "http://json-schema.org/draft/2020-12/schema"
    at Ajv.validate (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/node_modules/ajv/dist/core.js:147:1)
    at Ajv.validateSchema (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/node_modules/ajv/dist/core.js:260:1)
    at Ajv._addSchema (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/node_modules/ajv/dist/core.js:460:1)
    at Ajv.compile (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/node_modules/ajv/dist/core.js:158:1)
    at schema (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/src/functions/json-validator.js:25:1)
    at jsonValidator (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/src/functions/json-validator.js:49:1)
    at run (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/src/main.js:7:1)
    at /home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/webpack:/json-yaml-validate-action/src/main.js:14:1
    at /home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/dist/index.js:43402:3
    at Object.<anonymous> (/home/runner/work/_actions/GrantBirki/json-yaml-validate/v1.5.0/dist/index.js:43405:12)
```

**Comment by GrantBirki** [comment]
This is indeed a pretty funky error. I posted a comment on your other issue and I _think_ upgrading to the latest release of this Action _may_ help. At the very least, it will help with debugging.

I recently merged a PR that was originally designed by a new contributor and I think it may help with `ajv` issues as well -> https://github.com/GrantBirki/json-yaml-validate/pull/22

**Comment by thushan** [comment]
Freaky, I just came [across the same thing](https://github.com/matterfusion/matter-db/commit/d2926f140183dff573b6e59e2298516c7a0e357b) must be that time of the day/night.

**Comment by GrantBirki** [comment]
@thushan Can you re-run that CI job on version `v2.1.0` with debugging enabled? Then can you link the run here? I'll take a look and see if anything is jumping out as a potential issue 👀

**Comment by thushan** [comment]
@GrantBirki can do, how do I enable debugging, can't see the setting to use. But can do!

**Comment by JohnnyJayJay** [comment]
> @GrantBirki can do, how do I enable debugging, can't see the setting to use. But can do!

You have to rerun the failed job and tick the checkbox to enable it.

I've done it on my end, here's the [result](https://github.com/codosseum-org/challenges/actions/runs/5821035610/job/15782692018):

```
##[debug]use_gitignore: true - only using git tracked files
Warning: error reading .gitignore file: Error: ENOENT: no such file or directory, open '.gitignore'
##[debug]using ajv-formats with json-validator
```
This is the only output before the backtrace.

**Comment by thushan** [comment]
> You have to rerun the failed job and tick the checkbox to enable it.

Cool, I thought there was maybe something extra. [Re-ran the job](https://github.com/matterfusion/matter-db/actions/runs/5821079290/job/15782866856), but [the logs](https://pipelines.actions.githubusercontent.com/serviceHosts/ab03fd19-f10d-48b1-bdca-2e7127c6c503/_apis/pipelines/1/runs/8/signedlogcontent/2?urlExpires=2023-08-10T12%3A33%3A42.4227120Z&urlSigningMethod=HMACV1&urlSignature=nTdnlDD1GBK6Za9By1oQNtRIIn0jGh3yHbcmnBXjq4o%3D) don't tell me much either like @JohnnyJayJay.

Let us know how to assist.

**Comment by GrantBirki** [comment]
I may need to "phone a friend" and by "friend" I mean the _open source community_ on this one.

To be honest, I built this Action to simply check _if a JSON file is valid or not_. I have a few projects where less tech savvy folks would open PRs missing a `{` or something and it wouldn't get caught until after the PR merged. This Action fixes that core issue by validating JSON files, but I thought it would be nice to go one step further and have a way to also validate against schemas.

It should be noted that I don't really have a ton of experience validating schemas and I'm totally lost with what this error message is about.

I'll try my best to help, push commits with code suggestions, and help you guys debug but I'll need some extra assistance on this front!

---

Here are some details that may help get the ball rolling for us to fix this bug.

- This Action uses `ajv` as its JSON schema validator
- The code for how we setup `ajv` in this project can be found [here](https://github.com/GrantBirki/json-yaml-validate/blob/93172d1e4fa3579d6c397ed1f878ce0248771360/src/functions/json-validator.js#L8-L36)
- A few other folks on stackoverflow found talking about a [similar issue](https://stackoverflow.com/questions/66534011/no-schema-with-key-or-ref-with-ajv-when-validating-schema-property)
- Some blog that also talks about [json schema validation](https://www.technicalfeeder.com/2021/11/validate-json-file-with-json-schema/?utm_content=cmp-true) that seems to sound familiar (tons of ads though 🤮)

**Comment by thushan** [comment]
No probs, let me have a looksy on the weekend. I've not used `ajv` properly yet.

**Comment by thushan** [comment]
Hey @GrantBirki, took a looksy around this but I think it may be a `ajv` issue with our schema being `draft/2020-12/schema`. I'm not too familiar with writing actions for Github, only using them so went old school and wrote a nodeapp.

I tried some of the schemas I wrote (draft) and @JohnnyJayJay's [challenger-schema.json](https://github.com/codosseum-org/challenges/blob/c0e736069af45848cc2b4b49003783a2396599c3/challenge-schema.json) on a super simple `ajv` node script and it spat out the same exception.

It's not our files as far as I can tell, because i checked both via json.net and [jsonschemavalidator](https://www.jsonschemavalidator.net/) (uses NewtonSoft's JSON.NET) and they parse fine.

**Comment by GrantBirki** [comment]
@thushan Well that is quite tricky then as we really don't have much control outside of a PR to the source of `ajv` which will get merged _who knows when_. I guess the options are either one of the following:

- Use a different schema (non-draft?) to avoid the issue - not entirely sure if this is accurate advice as I'm kinda unfamiliar here
- Use a different node based json schema parser that doesn't contain this bug

Thoughts?

**Comment by GrantBirki** [comment]
Hmm so I'm wondering if this Action may need to move away from using `ajv` then? I'll do some searching to see if others have run into this issue with `ajv` and if they have solved it

**Comment by GrantBirki** [comment]
Hmm well I'm going to go down this rabbit hole now 🐰 

<img width="675" alt="Screenshot 2023-08-14 at 10 31 01 PM" src="https://github.com/GrantBirki/json-yaml-validate/assets/23362539/cebfa5b2-e1e8-408d-9ba6-b4c248e94eaa">

https://ajv.js.org/json-schema.html

**Comment by GrantBirki** [comment]
Well I found the answer:

https://ajv.js.org/json-schema.html#draft-2020-12

<img width="802" alt="Screenshot 2023-08-14 at 10 32 24 PM" src="https://github.com/GrantBirki/json-yaml-validate/assets/23362539/83563929-ae1b-454c-bb8d-9b5c85eaab2d">

**Comment by GrantBirki** [comment]
I have an idea for how to fix this and will open a pull request shortly 🌟

**Comment by GrantBirki** [comment]
@thushan and @JohnnyJayJay, I have published [`v2.3.0`](https://github.com/GrantBirki/json-yaml-validate/releases/tag/v2.3.0) of this Action which _should_ solve all your problems. Please update to that version, and ensure you set `json_schema_version: "draft-2020-12"` and see if that works!

If it works please let me know here, and if it doesn't - reopen this issue and I'll take another look. Thanks! ❤️

**Comment by thushan** [comment]
nicely done! not long after I posted that I went through their repo and docs & found the same and it defo worked locally (once we invoke AVJ as per the example in the docs) and I left some errors to validate that... I just got off a long flight but will give it ago  properly when I get into work - posted that _just_ before we departed! 

was waiting and waiting in excitement till we land to post we may have a w orkaround but requires a new config.

Nicely done, I think we can close this sooooooon!

**Comment by thushan** [comment]
Great stuff @GrantBirki, [it's working](https://github.com/matterfusion/matter-registry/actions/runs/5861594153/job/15891947570). There's an issue with `qt-uri-protocols` being  used for URIs but that means it's actually parsing it :)

Co-incidentally, the [docs initially state](https://ajv.js.org/guide/schema-language.html#draft-2019-09-and-draft-2020-12) to use this:

![image](https://github.com/GrantBirki/json-yaml-validate/assets/68254/1cdece2b-9c4e-4ee9-a953-65b5a7fc00b7)

I just assumed 2019 also had 2020 support initially  until looking deeper and realising 2020 is not backwards compatible and found your API reference doc example!

Thanks so much! Got there in the end.

**Comment by thushan** [comment]
Amazing [it's working](https://github.com/matterfusion/matter-registry/pull/1).

well done @GrantBirki!

**Comment by JohnnyJayJay** [comment]
Thank you, @GrantBirki !
