### ISSUE TITLE
More user-friendly error message

### ISSUE THREAD

**Issue by VictoriousRaptor** [GrantBirki/json-yaml-validate#37]
Currently the error report  doesn't show line number, making it very hard to locate the error, especially for big files. For example, if an item in array violates some rule, it just shows the index of the item in the array.
![Clip_20230927_184657](https://github.com/GrantBirki/json-yaml-validate/assets/10308169/618335c8-c4c3-469b-b1be-a70b57ef2139)

**Comment by GrantBirki** [comment]
> Currently the error report doesn't show line number

Unfortunately, this project won't be able to display the line number on which the error occurred. This action uses `ajv` for JSON validation and it cannot fetch line numbers by design -> https://github.com/ajv-validator/ajv/issues/1768
