### ISSUE TITLE
Feature: Allow multiple documents in YAML

### ISSUE THREAD

**Issue by bbompk** [GrantBirki/json-yaml-validate#39]
## Background and Objective:
I recently worked on a repository where I need to store multiple k8s manifest files; where 90% of the code is YAML lol. It is very common to include 2 documents in a manifest like deployment and service. And I would like to simply just validate the YAML files with every pushes. 

I would like to contribute to this project, just recently forked and made a draft change. I would really appreciate if I could open a PR for a review ?

**Comment by GrantBirki** [comment]
@bbompk Pull requests are absolutely welcome! Feel free to open one with your feature and I will give it a review :star:

**Comment by GrantBirki** [comment]
@bbompk Changes are included in the latest release! [`v2.4.0`](https://github.com/GrantBirki/json-yaml-validate/releases/tag/v2.4.0) :tada:
