### ISSUE TITLE
Feature request: Support non-strict mode of AJV

### ISSUE THREAD

**Issue by rlh1994** [GrantBirki/json-yaml-validate#48]
Sometimes my jsonschema has additional fields such as version or title, but this causes ajv to error as it is on strict mode. It would be nice to have an option to run it in non strict mode

https://ajv.js.org/strict-mode.html#unknown-keywords

**Comment by GrantBirki** [comment]
Thanks for the suggestion! ❤️ 

I have added this in [`v2.6.0`](https://github.com/GrantBirki/json-yaml-validate/releases/tag/v2.6.0). Go ahead and try it out and let me know what you think. Feel free to either re-open this issue or create a new one if the latest release is not working as expected. Thanks!
