### ISSUE TITLE
How to validate schema for various files?

### ISSUE THREAD

**Issue by djrmarques** [GrantBirki/json-yaml-validate#6]
For example, if I have the following project structure:

```
- data/
  - file1.json
  - file2.json
  - another_folder/
    - other_file_1.yaml
    - other_file_2.yaml
```    

How can I setup schema validation? 
It seems that the action only let's me specify a single schema validation file, via the `json_schema` and `yaml_schema` parameters, but  how do I set it up if I have various file across my repo?

Thank you :)

**Comment by GrantBirki** [comment]
Sounds like this is something that we need then! I will be tracking work on this here: https://github.com/GrantBirki/json-yaml-validate/issues/7

cc: @Can-Sahin + @djrmarques

**Comment by djrmarques** [comment]
I think it would be nice to implement something like the following.

```
- data/
  - file1.json
  - file2.json
  - file1.schema.json
  - another_folder/
    - other_file_1.yaml
    - other_file_1.schema.yaml    
    - other_file_2.yaml
    - other_file_2.schema.yaml
```

This way, the action would allow to define a schema in the same folder as the files. 

I can try and make a PR with this depending on how much time I have on the weekend.

**Comment by Can-Sahin** [comment]
If you enforce file namings or directory structure to use this action I'm pretty sure nobody will use this action. It's kinda absurd to enforce such a thing :) 

List of input json files and map of their schema files is the way to go.

**Comment by djrmarques** [comment]
Not enforce, it would be an option. I think this would make sense in some cases, given that you could add schema files without changing the action code. You could give an option for defining the suffix of the files that should be considered schemas. 

Anyways, I also agree that your suggestion is a good one.
