### ISSUE TITLE
Action should only validate files versioned on git

### ISSUE THREAD

**Issue by djrmarques** [GrantBirki/json-yaml-validate#9]
I really value the feature that this action validates the format of `json` and `yaml` files across my repo, even those without an enforced schema. However, in my opinion, the action should just validate files that are versioned on git, and not other files that are created in the action runtime, for example, `node_modules/**/*json` files. This should be an easy fix I think, if you agree it makes sense.

PS: Sorry for opening so many issues lately, I just find this action really useful :).

**Comment by GrantBirki** [comment]
Totally agree! I think this feature should be added, and a pretty easy one to implement as well

**Comment by GrantBirki** [comment]
I will be working on this feature in the pull request linked below

cc: @djrmarques
